apiVersion: batch/v1
kind: Job
metadata:
  name: cuda-vector-add
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: cuda-vector-add
          image: "k8s.gcr.io/cuda-vector-add:v0.1"
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never
