apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: gpu-test
        image: ubuntu
        command: ["nvidia-smi"]
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
     
